# .streamlit/secrets.toml
# Substitua os valores abaixo pelas suas credenciais do Google Cloud

[gcp_service_account]
type = "service_account"
project_id = "seu-project-id"
private_key_id = "seu-private-key-id"
private_key = "-----BEGIN PRIVATE KEY-----\nSUA_CHAVE_PRIVADA_AQUI\n-----END PRIVATE KEY-----\n"
client_email = "seu-email-service-account@seu-project.iam.gserviceaccount.com"
client_id = "seu-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/seu-email-service-account%40seu-project.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
